name = "QuantumControlExamples"
uuid = "cf1c7e0c-791d-49c7-9c9f-8a93147f9ca8"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "0.1.0-dev"

[deps]
DisplayAs = "0b91fe84-8a4c-11e9-3e1d-67c38462b6d6"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
GRAPE = "6b52fcaf-80fe-489a-93e9-9f92080510be"
GRAPELinesearchAnalysis = "290eba36-e2d8-4488-81b6-f66cc44f2186"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Krotov = "b05dcdc7-62f6-4360-bf2c-0898bba419de"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantumControl = "8a270532-f23f-47a8-83a9-b33d10cad486"
QuantumControlBase = "f10a33bc-5a64-497c-be7b-6f86b4f0c2aa"
QuantumControlTestUtils = "d3fd27c9-1dfb-4e67-b0c0-90d0d87a1e48"
QuantumPropagators = "7bf12567-5742-4b91-a078-644e72a65fc1"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TwoQubitWeylChamber = "cad078a0-0012-46f4-b55e-a945d44e115b"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
DisplayAs = "0.1.6"
Documenter = "1.2"
DocumenterCitations = "1.3"
DocumenterInterLinks = "0.2"
GRAPE = "0.6.0"
GRAPELinesearchAnalysis = "0.6.0"
Glob = "1.3"
JuliaFormatter = "1.0"
Krotov = "0.6.0"
LineSearches = "7.2"
LinearAlgebra = "1"
Literate = "2.16"
LiveServer = "1.2"
Optim = "1.7"
Plots = "1.39"
QuantumControl = "0.9.0"
QuantumControlBase = "0.9.1"
QuantumControlTestUtils = "0.3.0"
QuantumPropagators = "0.7.3"
SafeTestsets = "0.1"
SparseArrays = "1.10"
TOML = "1"
Test = "1"
TwoQubitWeylChamber = "0.1.3"
UnicodePlots = "3.6"
Zygote = "0.6"
julia = "1.10"
